### ISSUE TITLE
Any further implementation?

### ISSUE THREAD

**Issue by sumyatthitsarr** [mdcramer/Deep-Speeling#10]
Have you implemented anything so far better than this model?

**Comment by mdcramer** [comment]
I have not, but thank you for asking. This was basically a little side project for fun. I wrote about it at https://mdcramer.github.io/deep-speeling-blog/.

**Comment by sumyatthitsarr** [comment]
@mdcramer I would like to ask one more question. Do you have any experiences to build a spell corrector using a character level language model? Or any other redirections to any useful blog would be appreciated. Thank you for answering.

**Comment by mdcramer** [comment]
@Wickky, my pleasure. Unfortunately I do not. If you check out https://mdcramer.github.io/deep-speeling-blog/conclusion/, in the end I wasn't able to get this project to work particularly well. While it was fun to learn about deep learning, my guess is that training a model like this probably isn't the most efficient way to fix spelling. It just seems like using a dictionary would be the best way to go. That is, after all, what we do in real life.
